// Bundles mcp/server.ts (plus the SDK's reachable stdio code and zod) into a single
// self-contained mcp/server.bundle.mjs. The bundle ships with the plugin and runs at
// runtime with zero node_modules — no npm install on the user's machine.
//
// Rebuild after changing mcp/server.ts, scripts/db.ts, or bumping a devDependency:
//   npm install   (needs NODE_OPTIONS=--use-system-ca behind a TLS-intercepting proxy)
//   npm run build
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [resolve(root, "mcp/server.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  // node: builtins are auto-externalized on platform:node; node:sqlite listed for clarity.
  external: ["node:sqlite"],
  outfile: resolve(root, "mcp/server.bundle.mjs"),
  banner: {
    js: "// AUTO-GENERATED by `npm run build` from mcp/server.ts — do not edit by hand.",
  },
});

console.log("Built mcp/server.bundle.mjs");
